name: Linux Build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  linux:
    name: Linux x64
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: krdlab/setup-haxe@d93667502be3b4f31a94a3308a74388f2e178a8d # v2.1.0
        with:
          haxe-version: 4.2.5
          cache-dependency-path: hmm.json

      - name: Restore build cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: export/release/linux
          key: seiu-export-linux-x64-v1-${{ hashFiles('Project.xml', 'hmm.json') }}

      - uses: ./.github/actions/build-desktop
        with:
          target: linux
          rebuild: haxelib run lime rebuild linux -64 -release -Dlime-sdl3
          build: haxelib run lime build linux --app-version="$APP_VERSION-$GITHUB_RUN_ID"
          artifact: SeiunEngine-linux-x64
          path: export/release/linux/bin
          gh-pat: ${{ secrets.GH_PAT }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SeiunEngine-linux-x64
          path: export/release/linux/bin
          if-no-files-found: error
          retention-days: 14
